### ISSUE TITLE
events changements 

### ISSUE THREAD

**Issue by Mxxxxxxxxxxx** [otherplane/lisbon-blockchain-week#10]
Hello , I am the organiser of several events around liscon and there is some little mistakes on the calendar . Here it is the overview of them : 

<img width="327" alt="Capture d’écran 2021-09-20 à 16 11 45" src="https://user-images.githubusercontent.com/91057474/134017238-f979c9db-0c8c-41d3-9e78-f01f8fcccfbc.png">

**Comment by Mxxxxxxxxxxx** [comment]
Hello there I will resubmit my events so you will be able to delete previous ones

**Comment by aesedepece** [comment]
@Mxxxxxxxxxxx no problem!
